$(document).ready(function(){
  $("#development-image").click(function(){
    $("#development-image").hide();
    $("#development").show();
  });
  $("#development").click(function(){
    $("#development").hide();
    $("#development-image").show();
  });
});

$(document).ready(function(){
  $("#design-image").click(function(){
    $("#design-image").hide();
    $("#design").show();
  });
  $("#design").click(function(){
    $("#design").hide();
    $("#design-image").show();
  });
});

$(document).ready(function(){
  $("#product-image").click(function(){
    $("#product-image").hide();
    $("#product").show();
  });
  $("#product").click(function(){
    $("#product").hide();
    $("#product-image").show();
  });
});