$(document).ready(function(){
  $("#development-image").click(function(){
    $("#development-image").hide();
    $("#development").show();
  });
});
$(document).ready(function(){
  $("#development").click(function(){
    $("#development").hide();
    $("#development-image").show();
  });
});
$(document).ready(function(){
  $("#design-image").click(function(){
    $("#design-image").hide();
    $("#design").show();
  });
});
$(document).ready(function(){
  $("#design").click(function(){
    $("#design").hide();
    $("#design-image").show();
  });
});